service: aoc-slack-notifier
provider:
  name: aws
  runtime: java11
  timeout: 10
  region: ${opt:region, 'eu-west-2'}
  environment:
    DYNAMODB_TABLE: AOC_Polling_Event
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
package:
  artifact: target/slack-notifier-0.0.1-SNAPSHOT-aws.jar
functions:
  polling:
    handler: com.ctl.aoc.slacknotifier.handlers.PollingHandler
    events:
      - schedule: rate(1 minute)
    environment:
      FUNCTION_NAME: pollingFunction
      AOC_LEADERBOARD_ID: ${opt:leaderboardid}
      AOC_YEAR_EVENT: ${opt:year}
      AOC_SESSION_ID: ${opt:sessionid}
resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: identifier
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: identifier
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}